// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0_9Mku6eaf6UuvbRCkALuzNbulZXi9zU',
    appId: '1:597792868953:web:bcad76be0006685a603f48',
    messagingSenderId: '597792868953',
    projectId: 'to-do-app-1453b',
    authDomain: 'to-do-app-1453b.firebaseapp.com',
    storageBucket: 'to-do-app-1453b.firebasestorage.app',
    measurementId: 'G-V170MPXTKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7OjCbnEcCqYpfaVgxFVHD-dknx1HDfUU',
    appId: '1:597792868953:android:23230f62eaffaa11603f48',
    messagingSenderId: '597792868953',
    projectId: 'to-do-app-1453b',
    storageBucket: 'to-do-app-1453b.firebasestorage.app',
  );
}
